# Generated by Django 6.0.2 on 2026-03-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_withdrawalrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_bonus_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
