# Generated by Django 6.0.2 on 2026-03-06 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_profile_last_bonus_date_profile_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='requires_proof',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='proofs/'),
        ),
        migrations.AddField(
            model_name='taskcompletion',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
