# Generated by Django 6.0.2 on 2026-03-29 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_requires_proof_taskcompletion_proof_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_bonus_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
